version: "3"

services:
  db:
    image: mysql:8.0.13
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: docker/common/wait-for-it.sh db:3306 -- docker/ruby/entrypoint.sh
    volumes:
      - .:/myapp
      - bundle:/myapp/vendor/bundle
    ports:
      - 3000:3000
    env_file: .env
  redis:
    image: redis:5.0.3
    volumes:
      - redis-data:/data
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: docker/common/wait-for-it.sh redis:6379 -- docker/sidekiq/entrypoint.sh
    depends_on:
      - app
      - redis
    volumes:
      - .:/myapp
      - bundle:/myapp/vendor/bundle
    env_file: .env
volumes:
  db-data:
  bundle:
  redis-data: